#Name - Arjun A.
#Roll number - 181CO109
#Date of submission - 05-02-2021
This notebook was written in google colab. <br>Link to view notebook<br>
https://colab.research.google.com/drive/1JKaBdC9a9zcGfRst7EX_Vd8BgkcSQtmF?usp=sharing

#Machine Learning Lab 3
To demonstrate the usage of a naive Bayes classifier for a sample dataset. This is a classifier based on Bayes theorom. 

##Installing and Importing required packages

In [1]:
!pip install numpy
!pip install scipy
!pip install -U scikit-learn
!pip install pandas

Requirement already up-to-date: scikit-learn in /usr/local/lib/python3.6/dist-packages (0.24.1)


In [2]:
import numpy as np 
import pandas as pd 
from sklearn.model_selection import train_test_split 
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.datasets import load_wine

##Importing data from the wine dataset
Using the load_wine function from sklearn, importing the wine dataset


In [3]:
# Function to import data
def importdata(): 

  wineData = load_wine()
  X = wineData.data
  Y = wineData.target
  names = wineData.target_names
  featureName = wineData.feature_names
  print(type(X))
  print(type(Y))
  print(names)
  
  return X, Y, names, featureName

In [4]:
X, Y, wineClassNames, wineFeatureNames = importdata()

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
['class_0' 'class_1' 'class_2']


##Splitting the data into train and test sets
 Splitting the data in the ratio of 7:3. (70% training and 30% testing)

In [5]:
def splitdataset(X, Y): 

  X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.3, random_state = 100) #Specifying random_state to get the same dataset split everytime 
	
  return X, Y, X_train, X_test, y_train, y_test 

In [6]:
X, Y, X_train, X_test, y_train, y_test = splitdataset(X, Y)

#Use to print the entire dataset
#print(X, Y, X_train, X_test, y_train, y_test, sep = '\n\n')

#Printing size of the split
print('Test dataset size\nX_test -', len(X_test), '\ny_test -', len(y_test), '\n')
print('Train dataset size\nX_train -', len(X_train), '\ny_train -', len(y_train))

Test dataset size
X_test - 54 
y_test - 54 

Train dataset size
X_train - 124 
y_train - 124


##Function to measure accuracy 
Using sklearn's classification_report, confusion_matrix and accuracy_score.

In [7]:
def measuringAccuracy(y_test, y_predict):
  print('Accuracy -', (accuracy_score(y_test, y_predict) * 100))
  print('Report', classification_report(y_test, y_predict), sep = '\n')
  print('\nConfusion matrix\n', confusion_matrix(y_test, y_predict))

##Training the model on training set

In [8]:
model = GaussianNB() 
model.fit(X_train, y_train) 

GaussianNB()

##Calculating the accuracy of the model
The accuracy of the model is calculated based on the test data. 



In [9]:
y_pred = model.predict(X_test)
measuringAccuracy(y_test, y_pred)
print('', 'Class Names of the wine dataset', wineClassNames, '', 'Feature Names of the wine dataset', wineFeatureNames, sep = '\n')

Accuracy - 100.0
Report
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       1.00      1.00      1.00        19
           2       1.00      1.00      1.00        21

    accuracy                           1.00        54
   macro avg       1.00      1.00      1.00        54
weighted avg       1.00      1.00      1.00        54


Confusion matrix
 [[14  0  0]
 [ 0 19  0]
 [ 0  0 21]]

Class Names of the wine dataset
['class_0' 'class_1' 'class_2']

Feature Names of the wine dataset
['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'od280/od315_of_diluted_wines', 'proline']
